
title: Anil Khatri(@_imkaka)
name: Anil Khatri
email: anil.soccer.khatri@gmail.com
description: Anil Khatri's personal blog and portfolio website | Software Developer at Intern HPC Sphere | Exploring the CS World | Footballer from India.
baseurl: /
url: http://imkaka.github.io
twitter: _imkaka
github:  imkaka
linkedin: anil-khatri-0841223a
facebook: ak10s
hackerrank: imKaka
telegram: imkaka
stackoverflow: users/7793759/anil-khatri
khanacademy: ImKaka
google_analytics: UA-130957798-1


# Build settings
highlighter: rouge
markdown: kramdown
permalink: /:title.html
theme: minima
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
